export default {
    "cities": [
        { name: "Ba Seng Sei", 
            x : 40, 
            y : 6, 
            z : 40, 
            mat : "textures/earth.png",
            info : "bvhid" },
        { name: "Ginsen Temple", 
            x: 56, 
            y: 2, 
            z : 24, 
            mat : "textures/earth.png",
            info : "ewweirf" },
        { name: "Shai City", 
            x: -6, 
            y: 8, 
            z : 75, 
            mat : "textures/water.jpg",
            info : "xwnece" },
        { name: "The Library", 
            x: 30, 
            y: 4, 
            z : 5, 
            mat : "textures/earth.png",
            info : "kolp" },
        { name: "Shuen City", 
            x: -18, 
            y: 8, 
            z : -70, 
            mat : "textures/water.jpg",
            info : "weiuiefhre" }
        
    ],
}